# Generated by Django 3.2.7 on 2021-11-23 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_filestorevalue1_income_expense_ledgervalue1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileStore',
        ),
        migrations.DeleteModel(
            name='FileStoreValue',
        ),
        migrations.DeleteModel(
            name='Income_Expense_LedgerValue',
        ),
    ]
