# Generated by Django 3.2.7 on 2021-11-25 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_membersdeatils'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembersDeatilsValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flatNo', models.CharField(max_length=200)),
                ('primaryName', models.CharField(blank=True, max_length=200, null=True)),
                ('primaryContactNo', models.CharField(blank=True, max_length=10, null=True)),
                ('secondaryName', models.CharField(blank=True, max_length=200, null=True)),
                ('secondaryContactNo', models.CharField(blank=True, max_length=10, null=True)),
                ('accountingName', models.CharField(blank=True, max_length=200, null=True)),
                ('whatsappContactNo', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('residence', models.CharField(max_length=100)),
            ],
        ),
    ]
